// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'


    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrSkyKpTTNZDsooq5wCEiIuSLZ8X9dv14',
    appId: '1:75869691893:web:ae3c209d224006300e0abc',
    messagingSenderId: '75869691893',
    projectId: 'flut-68ef9',
    authDomain: 'flut-68ef9.firebaseapp.com',
    storageBucket: 'flut-68ef9.appspot.com',
    measurementId: 'G-VEXDBZWJY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJRz3vnonrPWGWDsiGteI7wlVYpCtLyrs',
    appId: '1:75869691893:android:22b7af683f63f2710e0abc',
    messagingSenderId: '75869691893',
    projectId: 'flut-68ef9',
    storageBucket: 'flut-68ef9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc7CHmbpZDsc1mXgV4cZDGCXlxOPfimGg',
    appId: '1:75869691893:ios:6d82b2fa4058a2850e0abc',
    messagingSenderId: '75869691893',
    projectId: 'flut-68ef9',
    storageBucket: 'flut-68ef9.appspot.com',
    iosBundleId: 'com.example.sign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc7CHmbpZDsc1mXgV4cZDGCXlxOPfimGg',
    appId: '1:75869691893:ios:f479a62c789f05f00e0abc',
    messagingSenderId: '75869691893',
    projectId: 'flut-68ef9',
    storageBucket: 'flut-68ef9.appspot.com',
    iosBundleId: 'com.example.sign.RunnerTests',
  );
}
